@startuml scafi3-architecture

skinparam component {
    BackgroundColor<<jvm-only>> #fadce8ff
    BackgroundColor<<pure>> #c0e5e7ff
    BackgroundColor<<full>> #e1f89aff-ffe993ff
}

component ":scafi3-core" as core <<pure>>

component ":scafi3-alchemist-incarnation" as alchemist <<jvm-only>>

component ":scafi3-distributed" as distributed <<full>>

component ":scafi3-polyglot-api" as polyglot <<full>>

component ":scafi3-integration" as integration <<test>>

core <|-- alchemist
core <|-- distributed
distributed <|-- polyglot
polyglot . integration

@enduml