@startuml socket-distribution

skinparam interface<<trait>> {
  BackgroundColor lightblue
  BorderColor blue
  StereotypeFontColor blue
}

package "core" {
    interface NetworkManager << (T,#b2a7e0) trait >> {
        + type DeviceId
        + send(message: Export[DeviceId])
        + receive(): Import[DeviceId]
    }
}

package "distributed" {
    package "shared" {
        ' object InetTypes {
        '     + type IPv4
        '     + type Port
        '     + type Hostname
        '     + type Endpoint
        '     + ...
        ' }

        interface ConnectionOrientedNetworking << (T,#b2a7e0) trait >> {
            + type MessageIn
            + type MessageOut
            + out(endpoint: Endpoint): Future[Connection]
            + in(port: Port)(onReceive: MessageIn => Unit): Future[ListenerRef]
        }
        ConnectionOrientedNetworking +-left- Connection
        ConnectionOrientedNetworking +- ListenerRef
        ListenerRef +- Listener

        interface Connection << (T,#b2a7e0) trait >> {
            + send(message: MessageOut): Future[Unit]
            + close()
        }

        class ListenerRef {
            + listener: Listener
            + accept: Future[Unit]
        }

        interface Listener << (T,#b2a7e0) trait >> {
            + boundPort: Port
            + close()
        }

        interface ConnectionOrientedTemplate << (T,#b2a7e0) trait >> extends ConnectionOrientedNetworking {
            + type MessageIn : BinaryDecodable
            + type MessageOut : BinaryEncodable
        }
        note right of ConnectionOrientedTemplate
            Template class 
            implementing common 
            platform-agnostic logic
        end note

        interface NeighborhoodResolver << (T,#b2a7e0) trait >> {
            + type Neighborhood[DeviceId] = Set[DeviceId]
            + neighborhood: Neighborhood[DeviceId]
        }

        interface ConnectionOrientedNetworkManager << (T,#b2a7e0) trait >> extends ConnectionOrientedNetworking
        ConnectionOrientedNetworkManager *-left-> NeighborhoodResolver : mixed in
        core.NetworkManager <|--- ConnectionOrientedNetworkManager

        object SocketNetworkManager << object>> {
            + withFixedNeighborhood[DeviceId](deviceId: DeviceId, port: Port, neighbors: Map[DeviceId, Endpoint])
        }
        note left of SocketNetworkManager
            Socket-based network
            manager entry-point
        end note
        SocketNetworkManager .up.> ConnectionOrientedNetworkManager
    }

    package "jvm-native" {
        interface SocketNetworking << (T,#b2a7e0) trait >>
        SocketNetworking --up-|> distributed.shared.ConnectionOrientedTemplate
        note bottom of SocketNetworking
            JVM-native socket-based implementation
        end note
    }

    package "js" {
        interface SocketNetworking << (T,#b2a7e0) trait >> 
        SocketNetworking --up-|> distributed.shared.ConnectionOrientedTemplate
        note bottom of SocketNetworking
            JavaScript socket-based implementation
        end note
    }

}

@enduml